In [79]:
import numpy as np
import pandas as pd

# Given list
matrix_data = [0.9999999980287146, 9.53682849715935e-07, 6.278265099961394e-05, 0.0, 9.53682849715935e-07, 0.9999999980287146, -6.278265099961394e-05, 0.0, 6.278265097886907e-05, 2.1782289481657688e-08, -0.9999999980291692, 0.0, 2.1782289481657688e-08, 6.278265097886907e-05, 0.9999999980291692, 0.0, -9.536842153862658e-07, 0.999999999999545, 2.172241470122033e-08, 0.0, 0.999999999999545, -9.536842153862658e-07, -2.172241470122033e-08, 0.0, -2.3842071242898373e-07, 0.24999999950717866, -1.6543612251060553e-24, 6.278265099961394e-05, -0.24999999950717866, 2.3842071242898373e-07, -1.6543612251060553e-24, -6.278265099961394e-05, -5.4455723704144235e-09, 1.569566274471727e-05, -5.048709793414476e-29, -0.9999999980291692, -1.569566274471727e-05, 5.4455723704144235e-09, -5.048709793414476e-29, 0.9999999980291692, -0.24999999999988626, -2.384210538465665e-07, 3.3881317890172014e-21, 2.172241470122033e-08, 2.384210538465665e-07, 0.24999999999988626, 3.3881317890172014e-21, -2.172241470122033e-08]


# Reshape into a 6x6 matrix
matrix = np.array(matrix_data).reshape(6, 8)

# Convert the matrix to a pandas DataFrame for better visualization
matrix_df = pd.DataFrame(matrix)

from IPython.display import display
print("G Matrix:")
display(matrix_df)
print("Determinant of the matrix:", np.linalg.det(matrix))
np.linalg.det(matrix)
print("Inverse of the G matrix:")


G Matrix:


0             1             2             3             4  \
0  1.000000e+00  9.536828e-07  6.278265e-05  0.000000e+00  9.536828e-07   
1  6.278265e-05  2.178229e-08 -1.000000e+00  0.000000e+00  2.178229e-08   
2 -9.536842e-07  1.000000e+00  2.172241e-08  0.000000e+00  1.000000e+00   
3 -2.384207e-07  2.500000e-01 -1.654361e-24  6.278265e-05 -2.500000e-01   
4 -5.445572e-09  1.569566e-05 -5.048710e-29 -1.000000e+00 -1.569566e-05   
5 -2.500000e-01 -2.384211e-07  3.388132e-21  2.172241e-08  2.384211e-07   

              5             6             7  
0  1.000000e+00 -6.278265e-05  0.000000e+00  
1  6.278265e-05  1.000000e+00  0.000000e+00  
2 -9.536842e-07 -2.172241e-08  0.000000e+00  
3  2.384207e-07 -1.654361e-24 -6.278265e-05  
4  5.445572e-09 -5.048710e-29  1.000000e+00  
5  2.500000e-01  3.388132e-21 -2.172241e-08

LinAlgError: Last 2 dimensions of the array must be square

In [65]:
import tf.transformations as tft
import numpy as np

# Given quaternion values
quaternion = (
    -0.0006492332642375155,  # x
    -0.00035469609910348827,  # y
    0.00048480506254222757,   # z
    0.9999996088253722        # w
)

# Use tf's quaternion_matrix to convert quaternion to a 4x4 transformation matrix
rotation_matrix = tft.quaternion_matrix(quaternion)

# Extract the 3x3 rotation matrix part
rotation_matrix_3x3 = rotation_matrix[:3, :3]

# Display the 3x3 rotation matrix
display(pd.DataFrame(rotation_matrix_3x3))


0         1         2
0  0.999999 -0.000969 -0.000710
1  0.000970  0.999999  0.001298
2  0.000709 -0.001299  0.999999

In [71]:
flattened_matrix = [
    0.9999980545162017, 0.0004682219393582945, 0.0019161764081518404,
    0.001915485711870842, 0.0014711695997115814, -0.9999970832829946,
    -0.00047103959416675917, 0.999998808213402, 0.0014702698651401355
]

# Reshape into a 3x3 matrix
matrix = np.array(flattened_matrix).reshape(3, 3)

# Assign to s(i), n(i), t(i)
s_i = matrix[:, 0]  # first column
t_i = matrix[:, 1]  # second column
n_i = matrix[:, 2]  # third column

display(pd.DataFrame(matrix))

0         1         2
0  0.999998  0.000468  0.001916
1  0.001915  0.001471 -0.999997
2 -0.000471  0.999999  0.001470

In [72]:
bi_l = np.array([0, 0.25, 0.0]) 
bi_r = np.array([0, -0.25, 0.0])  

In [73]:
first_column = np.cross(np.dot(rotation_matrix_3x3, bi_l),s_i)
display(pd.DataFrame(first_column))

0
0 -0.000117
1 -0.000325
2 -0.250000

In [74]:
second_column = np.cross(np.dot(rotation_matrix_3x3, bi_l),t_i)
display(pd.DataFrame(second_column))

0
0  0.250000
1  0.000242
2 -0.000117

In [78]:
third_column = np.cross(np.dot(rotation_matrix_3x3, bi_l),n_i)
display(pd.DataFrame(third_column))

0
0  4.286545e-05
1 -2.659595e-07
2 -2.367569e-04

In [16]:
import tf.transformations as tf
import csv
import numpy as np

In [4]:
def quaternion_to_angular_velocity(q1, q2, dt):
    """Computes angular velocity from the change in two quaternions."""
    q1_inv = tf.quaternion_inverse(q1)
    q_diff = tf.quaternion_multiply(q1_inv, q2)  # Relative quaternion
    angular_velocity = 2 * np.array(q_diff[:3]) / dt  # Divide by time step to get velocity
    return angular_velocity

In [9]:
def read_trajectory_and_compute_q_dot_d(csv_file, dt):
    trajectory_data = []

    # Reading the CSV file
    with open(csv_file, newline='') as csvfile:
        reader = csv.reader(csvfile)
        next(reader)  # Skip header row
        for row in reader:
            position_orientation = list(map(float, row))  # Convert all values to float
            trajectory_data.append(position_orientation)

    trajectory_data = np.array(trajectory_data)  # Convert to numpy array for easy manipulation

    # Initialize lists to store positions, orientations, and velocities
    positions = []
    orientations = []
    velocities = []

    # Compute q_dot_d (velocity) for each time step
    for i in range(1, len(trajectory_data)):
        # Store position (first 3 values)
        positions.append(trajectory_data[i][:3])  # Only positions (x, y, z)

        # Store orientation (last 4 values as quaternion)
        orientations.append(trajectory_data[i][3:])  # Only orientation (quaternion: x, y, z, w)

        # Difference in position (linear velocity)
        delta_position = trajectory_data[i][:3] - trajectory_data[i-1][:3]
        linear_velocity = delta_position / dt

        # Compute angular velocity from quaternion difference
        q_current = trajectory_data[i][3:]  # Current quaternion
        q_previous = trajectory_data[i-1][3:]  # Previous quaternion
        angular_velocity = quaternion_to_angular_velocity(q_previous, q_current, dt)

        # Combine linear and angular velocities
        q_dot_d = np.concatenate((linear_velocity, angular_velocity))
        velocities.append(q_dot_d)

    return positions, orientations, velocities

In [17]:
q_d_full_pos, q_d_full_ort, q_ddot_full = read_trajectory_and_compute_q_dot_d("box_trajectory.csv", 0.001)

In [18]:
q_d_full_pos[0]

array([3.00000438e-01, 3.52807754e-06, 1.10075533e+00])

In [20]:
q_d_full_ort[0]

array([ 1.87130281e-08, -5.11117233e-07,  8.09331080e-06,  1.00000000e+00])

In [21]:
q_ddot_full[0]

array([0.        , 0.        , 1.00049031, 0.        , 0.        ,
       0.        ])